version: '3'
services:
  transactiondb-1:
    image: rattransactiondb:latest
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=transactiondb-1
    networks:
      - ratnet

  transactiondb-2:
    image: ratslavedb
    command: /bin/bash -c "sleep 60 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=transactiondb-1
    networks:
      - ratnet

  transactiondb-3:
    image: ratslavedb
    command: /bin/bash -c "sleep 90 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=transactiondb-1
    networks:
      - ratnet

  auditdb:
    image: rattransactiondb:latest
        networks:
      - ratnet

  redis:
    image: redis
    networks:
      - ratnet

networks:
  ratnet: