version: '3'
services:
  audit:
    image: rataudit
    deploy:
      replicas: 1
    env_file:
      - variables.env

  transaction:
    image: rattransaction
    deploy:
      replicas: 3
    env_file:
      - variables.env
    ports:
      - "44440:44440"

networks:
  ratnet: