version: '3'
services:
  transactiondb:
    image: rattransactiondb
    restart: on-failure

  auditdb:
    image: ratauditdb
    restart: on-failure

  triggerdb:
    image: rattriggerdb
    restart: on-failure

  redis:
    image: redis
    restart: on-failure

  audit:
    image: rataudit
    restart: on-failure
    deploy:
      replicas: 1
    env_file:
      - variable.env

  transaction:
    image: rattransaction
    restart: on-failure
    deploy:
      replicas: 1
    env_file:
      - variable.env
    ports:
      - "44441:44441"

  trigger:
    image: rattrigger
    restart: on-failure
    deploy:
      replicas: 1
    env_file:
      - variable.env
