version: '3'
services:
  transactiondb:
    image: rattransactiondb

  auditdb:
    image: ratauditdb

  triggerdb:
    image: rattriggerdb

  redis:
    image: redis

  audit:
    image: rataudit
    deploy:
      replicas: 1
    env_file:
      - variable.env

  transaction:
    image: rattransaction
    deploy:
      replicas: 1
    env_file:
      - variable.env
    ports:
      - "44441:44441"

  webserver:
    image: ratwebserver
    deploy:
      replicas: 1
    env_file:
      - variable.env

  trigger:
    image: rattrigger
    deploy:
      replicas: 1
    env_file:
      - variable.env
