version: '3'
services:
  transactiondb-1:
    image: rattransactiondb
    restart: on-failure

  transactiondb-2:
    image: cassandra
    deploy:
      replicas: 2
    entrypoint:
      - "sh"
      - "-c"
      - "sleep 60 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=transactiondb-1

  auditdb:
    image: ratauditdb
    restart: on-failure

  triggerdb:
    image: rattriggerdb
    restart: on-failure

  redis:
    image: redis
    restart: on-failure

  audit:
    image: rataudit
    restart: on-failure
    deploy:
      replicas: 1
    env_file:
      - variable.env

  transaction:
    image: rattransaction
    restart: on-failure
    deploy:
      replicas: 1
    env_file:
      - variable.env
    ports:
      - "44441:44441"

  trigger:
    image: rattrigger
    restart: on-failure
    deploy:
      replicas: 1
    env_file:
      - variable.env
